In [2]:
import torch
from torch import nn
from torch.nn import functional as F

In [5]:
class CenteredLayer(nn.Module):
    def __init__(self):
        super().__init__()

    def forward (self, X):
        return X - X.mean()
    

layer = CenteredLayer()
res = layer(torch.FloatTensor([1, 2, 3, 4, 5]))
print(res)

tensor([-2., -1.,  0.,  1.,  2.])


In [ ]:
net = nn.Sequential(nn.Linear(4, 10))
Y = net(torch.randn(5,4))
Y1 = CenteredLayer()(Y)
print("Network0", Y, "\n")
print (Y.mean(), "\n")
print("Network1", Y1)

Network0 tensor([[-0.3168,  0.5355,  1.5844,  1.4004,  0.4885, -0.1448,  0.8560,  1.5220,
          0.0178, -0.8563],
        [ 0.5834, -0.4949, -0.3229, -0.2458,  0.1818,  0.3667,  0.1636,  0.0492,
         -0.3333,  0.1863],
        [-0.3046, -1.2474,  0.1836,  0.3933,  0.2722,  0.7804, -0.0867,  0.5469,
          0.1282, -0.1545],
        [ 0.2808, -1.4625, -0.9358,  0.6853, -0.0226,  1.5492, -0.2773, -0.5542,
          0.7626,  0.2564],
        [-0.2726, -0.2697,  1.0586,  0.2889,  0.4907, -0.0787,  0.4273,  1.2952,
         -0.4522, -0.4570]], grad_fn=<AddmmBackward0>) 

tensor(0.1609, grad_fn=<MeanBackward0>)
Network1 tensor([[-0.4777,  0.3746,  1.4235,  1.2395,  0.3276, -0.3057,  0.6951,  1.3611,
         -0.1431, -1.0172],
        [ 0.4225, -0.6557, -0.4838, -0.4067,  0.0210,  0.2058,  0.0027, -0.1117,
         -0.4942,  0.0254],
        [-0.4655, -1.4082,  0.0227,  0.2325,  0.1113,  0.6195, -0.2476,  0.3860,
         -0.0327, -0.3154],
        [ 0.1199, -1.6234, -1.0967,  0.52

In [11]:
class MyLinear(nn.Module):
    def __init__(self, input, out):
        super().__init__()
        self.weight = nn.Parameter(torch.randn(input, out))
        self.bias = nn.Parameter(torch.randn(out))
    
    def forward(self, X):
        linear = torch.matmul(X, self.weight.data) + self.bias.data
        return F.relu(linear)
    
linear = MyLinear(5, 3)
print(linear.weight)

Parameter containing:
tensor([[ 0.5750, -1.3687, -0.2861],
        [-0.0911,  0.9327, -1.0681],
        [-0.6827, -0.1331,  0.1352],
        [ 0.2203, -0.7335, -0.2411],
        [ 1.2612, -0.5088,  1.2597]], requires_grad=True)


In [21]:
net = nn.Sequential(MyLinear(64, 8), MyLinear(8, 1))
net(torch.randn(2, 64))

tensor([[1.8461],
        [0.0000]])